cargo-features = ["edition2024"]

[package]
name = "pinocchio-vault"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
borsh = "0.10.0"
mollusk-svm = "0.4.1" #1
pinocchio = "0.8.0"
pinocchio-pubkey = "0.2.4"
pinocchio-system = "0.2.3"
solana-sdk = "2.3.1" #2
